# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojoNinjas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dojo',
            old_name='desc',
            new_name='descript',
        ),
    ]
